### ISSUE TITLE
ReCo Fp16 training code files   

### ISSUE THREAD

**Issue by GiftNovice** [rfuruta/rfuruta.github.io#1]
Hello, I saw your question in the ReCo project, but I couldn't contact you. I also encountered the same problem, but I encountered NaN values when training with half precision. Could you please send me the code for fp16 training? Thank you very much.

**Comment by rfuruta** [comment]
I have never tried the ReCo training with fp16. In my case, I could successfully run the ReCo training with the default setting (i.e., fp32) on four or fewer A100 GPUs, where each has 40GB VRAM.

**Comment by GiftNovice** [comment]
OK!  Thanks!
